version: "3.8"

services:

   n8n:
    container_name:  cbw_n8n
    build:
      context: ./n8n
      dockerfile: Dockerfile
      
      
      ### alternative:
      ### docker compose build  --build-arg FILE_PWD="cbw"
      args:
       - FILE_PWD=cbw
        
        
        
    env_file:
      - .env      

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      

#    volumes:
#      - ./app-rewrite/src:/app/src
#      - ./app-rewrite/public:/app/public
#    restart: always
    ports:
      - 5678:5678
    depends_on:
      - apprewrite      
#    networks:
#      - my_network




   apprewrite:
    container_name: cbw_app
    build:
      context: ./app-rewrite
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./app-rewrite/src:/app/src
      - ./app-rewrite/public:/app/public
    restart: always
    ports:
      - 3000:3000
#    networks:
#      - my_network


  # Add more containers below (nginx, postgres, etc.)
  
  
  
  
  
  
  
  
  
  

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
#networks:
#  my_network:
#    external: true
