name: CI

on:


  push:
    branches: [ "main" ]
    
    
  release:
    types: [published]
  
    workflow_dispatch:    
    
jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    
    - name: sync src
      uses: actions/checkout@v3
      
    - name: export secrets
      run: export FILE_PWD=${{ secrets.FILE_PWD }}    
    
    - name: publish to registry
      #uses: pennsignals/publish_docker-compose@v0.2.6-rc.1
      uses: ascerb/publish_docker-compose@0.0.1
      with:
        #version: '0.1.1' # optional
        docker_compose: 'docker-compose.yml' # required
        repo_token: "${{ secrets.GITHUB_TOKEN }}"    



